version: '3'
services:
  jirat-crm_app:
    build: .
    ports:
      - "3023:3000"
    environment:
      - DB_URL=mongodb://mongo:27017/CRMdb
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
